name: $(date:yyyyMMdd)$(rev:.r)

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  dotNetCoreVersion3: 3.1.100
  dotNetCoreVersion2: 2.2.402
  cakeVersion: 0.36.0

trigger:
  - master
  - develop
  - bugfix/*
  - feature/*

pr:
  - master
  - develop

jobs:
  # Run Windows build and tests.
  - template: template/build.yml
    parameters:
      name: BuildAndTestsOnWindows
      displayName: Windows
      vmImage: windows-2019
      dotNetCoreVersion3: $(dotNetCoreVersion3)
      cakeVersion: $(cakeVersion)
      testFilter: FullyQualifiedName~DotNet.Testcontainers.Tests.Unit.Windows

  # Run Linux build and tests.
  - template: template/build.yml
    parameters:
      name: BuildAndTestsOnUnix
      displayName: Linux
      vmImage: ubuntu-18.04
      dotNetCoreVersion3: $(dotNetCoreVersion3)
      cakeVersion: $(cakeVersion)
      testFilter: FullyQualifiedName~DotNet.Testcontainers.Tests.Unit.Containers.Linux.TestcontainersContainerTest+With

  # Run static code analysis and publish artifact.
  # Until now, we do not cover Windows only tests.
  - ${{ if in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop') }}:
    - template: template/publish.yml
      parameters:
        name: Release
        displayName: Release
        vmImage: ubuntu-18.04
        dotNetCoreVersion3: $(dotNetCoreVersion3)
        dotNetCoreVersion2: $(dotNetCoreVersion2)
        cakeVersion: $(cakeVersion)
